spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: claims-service
          uri: http://localhost:8180
          predicates:
            - Path= /api/claims/**
        - id: policyservice
          uri: http://localhost:8181
          predicates:
            - Path= /api/policies/**
        - id: user-service
          uri: http://localhost:8080
          predicates:
            - Path= /api/users/**
        - id: payment-service
          uri: http://localhost:8089
          predicates:
            - Path= /api/payments/**
        - id: policy-service
          uri: http://localhost:8183
          predicates:
            - Path=/api/policies/**
        - id: notification-service
          uri: http://localhost:8087
          predicates:
            - Path= /api/notifications/**
 
 
server:
  port: 8085
 
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
 
 